default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: joel
  port: 5432

development:
  <<: *default
  database: Recipe_app

test:
  <<: *default
  database: Recipe_app_test

production:
  <<: *default
  database: Recipe_production
  username: Recipe_app
  password: <%= ENV["BLOG_DATABASE_PASSWORD"] %>
